### PR TITLE
Skip Callback functions

### PR DESCRIPTION
**Pull request by pjdufour**
This PR adds optional `SkipPathCallback` and `SkipSymbolicLinkCallback` functions that Walk will invoke before it stats a path or follows a symbolic link.  `SkipPathCallback` can be used to exclude a directory from walking, such as `/proc` or `/sys`.  `SkipSymbolicLinkCallback` can be used to avoid recursive loops.  Some file systems have symbolic link targets deep in a file structure, so you can't easily exclude a directory from the outside.  Example:

```
SkipPathCallback: func(pathname string) bool {
  return strings.HasPrefix("/proc", pathname)
},
SkipSymbolicLinkCallback: func(pathname string, target string) bool 
  return target == "." || strings.HasPrefix(target, "..")
}
```

### CODE REVIEW

**Comment by karrick** [comment]
Have you considered adding a guard in the callback function to handle ignoring specific file system nodes?

In general your callback function should be able to perform whatever special logic is needed for a particular use-case, and return the special value `file path.SkipDir` to direct the walk algorithm to not traverse further down a particular directory.

```Go
        Callback: func(osPathname string, de *godirwalk.Dirent) error {
            switch osPathname {
            case "/proc", "/sys":
                fmt.Printf("%s %s <- skipping\n", de.ModeType(), osPathname)
                return filepath.SkipDir
            }
            switch de.Name() {
            case ".git", ".svn":
                fmt.Printf("%s %s <- skipping\n", de.ModeType(), osPathname)
                return filepath.SkipDir
            }
            fmt.Printf("%s %s\n", de.ModeType(), osPathname)
            return nil
        },
```

**Comment by karrick** [comment]
Your guard clause can check the node type as well:

```Go
        Callback: func(osPathname string, de *godirwalk.Dirent) error {
            switch osPathname {
            case "/proc", "/sys":
                fmt.Printf("%s %s <- skipping\n", de.ModeType(), osPathname)
                return filepath.SkipDir
            }
            if de.IsSymlink() {
                target, err := os.Readlink(osPathname)
                if err != nil {
                    return err
                }
                if target == "." || strings.HasPrefix(target, "..") {
                    return filepath.SkipDir
                }
            }
            fmt.Printf("%s %s\n", de.ModeType(), osPathname)
            return nil
        },
```

**Comment by pjdufour** [comment]
I rebased and added an example that demonstrates the need to add additional functionality to handle recursive symlinks.  After testing it looks like symbolic links that points to itself is the primary problem area.  I added a panic to show the stacktrace.  You can run the example with:

```
go run examples/symlinks/main.go testdata_symlink_follow/c
```

Even though I intend to skip a symlink we still end up calling `os.Stat` (`github.com/karrick/godirwalk/walk.go:336` --> `symlinkDirHelper` --> `os.Stat`), because we want to find out whether to skip the file or directory.  I would like to avoid that extra system call.

I'm happy to try to find another way to solve this, but I'm not sure `filepath.SkipDir` encapsulates enough information.

**Comment by karrick** [comment]
@pjdufour , so I finally added build tests for linux, mac, and windows on every pull request, however, the test harness is not working properly on Windows right now. I will let you know once I get them working again.

https://github.com/karrick/godirwalk/issues/27#issuecomment-489736716

**Comment by karrick** [comment]
@pjdufour, earlier today I mentioned that I'd let you know that tests are working for linux, mac, and linux.

**Comment by karrick** [comment]
@pjdufour, I'm not sure where we left off here. Re-reading the issue, and re-reading `godirwalk` code, it still looks like having your callback function doing whatever logic it needs to do with respect to determining whether a directory or symbolic link to a directory should be skipped and returning `filepath.SkipDir` is the _proper_ thing to do. That's why when walk receives that response for the callback, it does the following:

```Go
    for _, deChild := range deChildren {
        osChildname := filepath.Join(osPathname, deChild.name)
        err = walk(osChildname, deChild, options)
        if err == nil {
            continue
        }
        if err != filepath.SkipDir {
            return err
        }
        // When received SkipDir on a directory or a symbolic link to a
        // directory, stop processing that directory but continue processing
        // siblings.  When received on a non-directory, stop processing
        // remaining siblings.
        isDir, err := isDirectoryOrSymlinkToDirectory(deChild, osChildname)
        if err != nil {
            if action := options.ErrorCallback(osChildname, err); action == SkipNode {
                continue // ignore and continue with next sibling
            }
            return err // caller does not approve of this error
        }
        if !isDir {
            break // stop processing remaining siblings, but allow post children callback
        }
        // continue processing remaining siblings
    }
```

The above logic is exactly how `filepath.Walk` handles a `filepath.SkipDir` return value, except for the symbolic link to directory logic, because `filepath.Walk` does not recurse to symbolic links to directories.

Anyways, please re-open this issue if you think there is something else that I am not addressing.

**Pull request closed without merging**
