### PR TITLE
Dirent.IsDirOrSymlinkToDir

### LINKED ISSUE #44: Dirent.IsDir() returns false for symlinks to directories
hi thank you for this project

i'm wondering how I can tell if a symlink to a directory is a directory, where in my case 
```
dirent.IsDir() = false
dirent.IsSymlink() = true
```

i think i saw a `isSymlinkToDirectory`, but it wasn't public

thanks!

`Linux manjaro 5.4.13-3-MANJARO #1 SMP PREEMPT Mon Jan 20 18:17:25 UTC 2020 x86_64 GNU/Linux`

### PR DESCRIPTION
**Pull request by karrick**
Closes #44

// IsDirOrSymlinkToDir returns true if and only if the Dirent represents a file
// system directory, or a symbolic link to a directory. Note that if the Dirent
// is not a directory but is a symbolic link, this method will resolve by
// sending a request to the operating system to follow the symbolic link.

### CODE REVIEW

**Comment by sentriz** [comment]
hi! thank you for doing this so quick. I've having trouble with it though. I have this example program

```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/karrick/godirwalk"
)

func callbackItem(path string, dirent *godirwalk.Dirent) error {
	isDir, err := dirent.IsDirOrSymlinkToDir()
	if err != nil {
		return fmt.Errorf("error in IsDirOrSymlinkToDir: %w", err)
	}
	fmt.Printf("processing %q, result: %v\n", path, isDir)
	return nil
}

func main() {
	log.Fatal(godirwalk.Walk(os.Args[1], &godirwalk.Options{
		Callback:            callbackItem,
		Unsorted:            true,
		FollowSymbolicLinks: true,
	}))
}
```

with the new `v1.15.0` tag, and this directory structure



now running the test program with arg "~/downloads/music"

```
processing "/home/senan/downloads/music", result: true
2020/01/28 17:29:09 error in IsDirOrSymlinkToDir: stat Frank Zappa: no such file or directory
```

so it seems like `de.path` is empty, and only `de.name` is there for there `os.Stat(filepath.Join(de.path, de.name))` - but not too sure

if I `cd` to `~/downloads/music`, the program works as expected (maybe only at a depth of 1, acting as a relative path?)

thanks!

**Comment by karrick** [comment]
@sentriz, thanks for the quick feedback. I also caught this exception after I pushed the change, and went ahead and pushed the next release out which should have that correction. Would you mind giving v1.15.2 a try?

**Comment by sentriz** [comment]
thank you very much :+1: seems to be working now

**Comment by karrick** [comment]
Great. I hope things work for you now. Let me know if you have any more problems with this.

**Pull request merged**
