### PR TITLE
Added an option to skip hidden files and directories.

### PR DESCRIPTION
**Pull request by cdemers**
I added a very simple option to skip hidden files, in my case it helped speed up the three walking a lot.
Thanks!

### CODE REVIEW

**Comment by uudashr** [comment]
The definition of hidden files  is not the same on different OS.
Ex: Windows file is hidden by it's attributes

Use `syscall.GetFileAttributes` and check whether it's `syscall.FILE_ATTRIBUTE_HIDDEN`


Actually this can be done on the Callback.
```go

callback := func(osPathname string, de *godirwalk.Dirent) {
  if osPathname[0] == "." {
    return filepath.SkipDir;
  }
  return nil
}
```

Create simple helper function can be used to achieve this kind of check.

IMHO better to keep the godirwalk clean, because this can be implemented on the user side. If somehow there are some bugs or things need to be changed, you don't have to wait the patch applied to godirwalk, instead everything can be updated on the user side.

**Comment by cdemers** [comment]
Hi! Thanks for your feedback, and you are right about Microsoft, I keep forgetting about that.
You are also absolutely right about the solution, I didn't notice the `SkipDir` option, I only saw `SkipNode` which obviously did not what I needed at the time.
Thanks again!

**Comment by cdemers** [comment]
Hi! I just noticed that the osPathname will most likely be somehting like this `/home/foo/bar/.hidden`.  I just used filepath.Base() on the osPathname:

```go
callback := func(osPathname string, de *godirwalk.Dirent) {
  base := filepath.Base(osPathname)
  if base[0] == "." {
    return filepath.SkipDir;
  }
  return nil
}
```

The PR solution would very likely be faster, not having to scan strings every iterations. In my case, I'm IO bound, so the cpu required to scan the string is not an issue, but someone walking on a good SSD might see a difference. I'll try it on my side.
Thanks again!

**Comment by uudashr** [comment]
maybe `de.Name()`? also give the same value

**Pull request closed without merging**
